config/routes.rb
Rails.application.routes.draw do
  root            'static_pages#home'
  get    'about'   => 'static_pages#about'
  post    'recent_meet' => 'static_pages#recent_meet'
  get   'show_all' => 'leagues#show_all'
  post  'scoring_rules' => 'static_pages#scoring_rules'
  post  'releaseMeet' => 'meets#releaseMeet'
  post 'scoreMeet' => 'meets#scoreMeet'
  get    'standings' => 'leagues#standings'
  get    'scoreboard'=> 'leagues#scoreboard'
  get    'myteam'  => 'leagues#myteam'
  get    'settings'=> 'leagues#settings'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'current_user' => 'sessions#show'
  delete  'meetdetail'  => 'meets#destroy'
  delete  'eventdetail'  => 'events#destroy'
  post    'addSelectedPlayer' => 'events#addSelectedPlayer'
  post    'showForUserInLeague' => 'events#showForUserInLeague'
  
  
  
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :meets
  resources :events do
    member do
      get :selectEntrant
      get :addEntrant
      get :removeEntrant
      get :enterResult
      post :claimAthlete
      post :dropAthlete
    end
  end
  resources :athletes
  
  resources :sprint_results
  resources :mid_results
  resources :jump_results
  resources :throw_results
  resources :league_settings
  resources :athlete_selections
  
  resources :leagues do
    member do
      get :searchLeague
      get :joinLeague
      post :addMember
      post :requestFriend
      get :inviteFriend
      get :boxScore
    end
  end
  resources :singleleague
  resources :league_messages,          only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  require 'nokogiri'
  require 'open-uri'
  
  def home
    if(logged_in?)
    
    end
  
      doc = Nokogiri::HTML(open("http://www.flotrack.org/"))
      @links = []
      @titles = []
      @srcs = []
      headlines = doc.css('section.headlines').css('div.figure-mask').map do |h|
        @links += [h.at_css("a")['href']]
        @titles += [h.at_css("img").attr('alt')]
        @srcs += [h.at_css("img").attr('src')]
      end

  end
  
  def about
    
  end
  
  def scoring_rules
  
  end
  
  def recent_meet
    if(logged_in?) 
      @availablemeets = []
      @meets = Meet.all()
      @meets.each do |meet|
        @availablemeets << meet if meet.released == true
      end
    else
      redirect_to root_url, notice: "Please log in to view recent meets!"
    end
  end
end
  

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<script>
$(document).ready(function (){
  $("#scrollTeam").click(function() {
    $('html, body').animate({
        scrollTop: $("#teamgallery").offset().top
    }, 1300);
  });
});
</script>  
<div class = "wrapper">
  <section class = container id = "about">
    <% provide(:title, 'About') %>  
    <h1>Hi, we're FantasyTrack</h1>
    <h4>Nice to meet you!</h4>
    <div class = "brief description" id = "description">
        <p>
          <h3>This is the fantasy Track Application<h2>
        </p>
        <p>We are Team 5. </p>
    </div>
    
    <h2><a class="btn btn-lg btn-success" id = "scrollTeam"  class="scroll">Meet the Team</a></h2>
    
  </section>  
    
  <section class="section--white video" id = "video">

    <div class="row">
      <div class="ten columns centered text-center">
        <h1 class="headline margin-bottom-35">Test About Video</h1>
         <div class="embed-container">  
            <iframe width="1100" height="600" src="//www.youtube.com/embed/8VloZp3KlMM" frameborder="0" allowfullscreen></iframe>
        </div>
      </div> <!-- /.ten.columns -->
    </div> <!-- /.row -->
  </section>


  <section class="container" id="teamgallery">

    <div class="row">
      <h3 class="headline">Meet the members</h3>
      <!-- START TEAM PICS -->
      

      <div class="three columns">
        <a class="member" href="//www.facebook.com/connor.early?fref=ts" title="Connor Ealry, UX Designer" rel="nofollow">
          <img src="//scontent-ord1-1.xx.fbcdn.net/hprofile-xtp1/v/t1.0-1/p160x160/12115764_10205274112914147_7249469749748587271_n.jpg?oh=9c1564b32e78a4643c6ac78a1ce8c3af&oe=56E9A7B3" alt="Connor Ealry"  width="200" height="200">
        </a>
        <p class="name"><strong>Connor Early</strong><br>UX Designer</p>
      </div>
      
      <div class="three columns">
        <a class="member" href="//www.linkedin.com/in/yujhuang" title="Yujun Huang, Style Designer" rel="nofollow">
          <img src="//scontent-ord1-1.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/12079606_686280878138018_4845238990101258312_n.jpg?oh=6f1d5f189cd2b26d09a6f995685cb671&oe=56E4DADA" alt="Leon" width="200" height="200">
        </a>
        <p class="name"><strong>Yujun Huang</strong><br>Styling Designer</p>
      </div>
      
      <div class="three columns">
        <a class="member" href="//www.facebook.com/nate.pierotti" title="Nate Pierotti, Developer" rel="nofollow">
          <img src="//scontent-ord1-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/11140302_10206686086497061_3258471862366113814_n.jpg?oh=67dfb80d0a2c57bf41d704508362ec2b&oe=56EAA0A6" alt="Nate Pierotti"  width="200" height="200" >
        </a>
        <p class="name"><strong>Nate Pierotti</strong><br>Developer</p>
      </div>
      
      <div class="three columns">
        <a class="member" href="//www.facebook.com/kevin.lewis.750" title="Kevin Lewis, Business Development Specialist" rel="nofollow">
          <img src="//scontent-ord1-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/10262106_10204092527691700_8903186002264955989_n.jpg?oh=bbaa81b710a8a491f0c41eece6ab4f53&oe=56B08408" alt="Kevin Lewis"  width="150" height="200" >
        </a>
        <p class="name"><strong>Kevin Lewis</strong><br>Business Development Specialist</p>
      </div>
      
      <div class="three columns">
        <a class="member" href="//www.facebook.com/profile.php?id=100009314271301&fref=ts" title="Xi Chen, developer" rel="nofollow">
          <img src="//scontent-ord1-1.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/12106956_1505832936403834_6639357143948508265_n.jpg?oh=985e611489ed13146aef2d3ac5225c66&oe=56ACCA8A" alt="Xi Chen"  width="200" height="200" >
        </a>
        <p class="name"><strong>Xi Chen</strong><br>developer</p>
      </div>
     

    </div>
  </section>
  
</div>

app/views/static_pages/adminHome.html.erb
<div class = "container" id = "asuser">
   <% provide(:title, 'Admin') %>
    <h2>You are an Administrator.</h2>
    <% provide(:title, @currentUser.user_id) %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <h1>
            <%= gravatar_for @currentUser %>
            <%= @currentUser.user_id %>
          </h1>
        </section>
      </aside>
    </div>
  </div>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
     <script>
       
        $(document).ready(function( ) {
          $("#firstslide").click(function() {
                document.location.href = "<%= @links[0]%>";
          })
          $("#secondslide").click(function() {
                document.location.href = "<%= @links[1]%>";
          })
          $("#thirdslide").click(function() {
                document.location.href = "<%= @links[2]%>";
          })
       });
       
     </script>
     
      <!-- Carousel
    ================================================== -->
     <% provide(:title, 'Home') %>
 <div class = "container" id = "hpnews">
   <center><strong><h2>Latest News</h2></strong></center>
    <div id="myCarousel">
      <!-- Indicators -->
      <table class = "table">
        <tbody>
          <tr id="firstslide"  >
            <td>
              <div >
                <img id= "image" src= <%=@srcs[0] %> />
              </div>
            </td>
            <td>
               <div>
                 <h1><%= @titles[0]%></h1>
               </div>
            </td>
          </tr>
          <tr id="secondslide" >
            <td>
              <div >
                <img id="image" src= <%=@srcs[1]%> />
              </div>
            </td>
            <td>
               <div>
                 <h1><%= @titles[1]%></h1>
               </div>
            </td>
          </tr>
          <tr id="thirdslide">
            <td>
              <div >
                <img id = "image" src= <%=@srcs[2]%>/>
              </div>
            </td>
            <td>
               <div>
                 <h1><%= @titles[2]%></h1>
               </div>
            </td>
          </tr>
        </tbody>
      </table>
      
    </div><!-- /.carousel -->
</div>

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->


    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <h2><%= link_to image_tag('twitter.jpg',size:'140x140',alt:"Generic placeholder image"), 'http://www.twitter.com', class:"img-circle" %></h2>
          <h2>Twitter</h2>
          <p><a class="btn btn-default" href="#" role="button">View details >></a></p>
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Rules</h2>
          <p>How to Play Fantasy Track</p>
          <p><%= button_to "Rules >>", scoring_rules_path, :id => "generalButton" %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Results</h2>
          <p>View Results from the last meet</p>
          <p><%= button_to "Results >>", recent_meet_path, :id => "generalButton" %></p>

        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->

    </div><!-- /.container -->
    
    <div class= "container users">
      <div class = "row">
        <br></br>
        <br></br>
        <center><h1> <%= User.count %> Users </h1> </center>
        <center> <h1> Already Signed up! </h1> </center>
        <br></br>
        <br></br>
      </div>
    </div>
    
    
    

app/views/static_pages/recent_meet.html.erb
<script>
    $(document).ready(function() {
    $('#example').DataTable();
    } );
</script>
<center><h1>Upcoming Meets</h1></center>
<div id = "divider">
    <div class = "container" id = "meets">
      <div>
         <br></br>
      </div>
      <div>
        <table id="example" class="display" cellspacing="0" width="100%">
            <thead>
                <td>Meet</td>
                <td>Location</td>
                <td>Start Date</td>
                <td>End Date</td>
            </thead>
            <tbody>
               <% @availablemeets.each do |p| %>
                <tr>
                    <td><%= link_to "#{p.meet_name}", meet_path(p), method: "get" %></td>
                    <td><%= p.location_city %>, <%= p.location_country %></td>
                    <td><%= p.start_date %></td>
                    <td><%= p.end_date %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>
</div>

app/views/static_pages/scoring_rules.html.erb
    <div class = "container"  id = "steps">
        <br></br>
        <br></br>
        <h1 align= "left"> Step 1: Sign Up!</h1>
        <p> Signing up is easy! Press the login button and fill out your information. Check your email for the confirmation email
        and get ready to compete against your friends.
        </p>
        <br></br>
        <br></br>
        <h1 align= "left"> Step 2: Form a League!</h1>
        <p> After you have logged in. Find the Join league tab and either join a friends league or create your own. There are plenty
        of options to choose from and there is no limit to how many friends you can invite!</p>
        <br></br>
        <br></br>
        <h1 align = "left"> Step 3: Compete!</h1>
        <p> Once your league has been formed, choose athletes to join your team and compete against your friends.</p>
      </div>