config/routes.rb
Rails.application.routes.draw do
  root            'static_pages#home'
  get    'about'   => 'static_pages#about'
  post    'recent_meet' => 'static_pages#recent_meet'
  get   'show_all' => 'leagues#show_all'
  post  'scoring_rules' => 'static_pages#scoring_rules'
  post  'releaseMeet' => 'meets#releaseMeet'
  post 'scoreMeet' => 'meets#scoreMeet'
  get    'standings' => 'leagues#standings'
  get    'scoreboard'=> 'leagues#scoreboard'
  get    'myteam'  => 'leagues#myteam'
  get    'settings'=> 'leagues#settings'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'current_user' => 'sessions#show'
  delete  'meetdetail'  => 'meets#destroy'
  delete  'eventdetail'  => 'events#destroy'
  post    'addSelectedPlayer' => 'events#addSelectedPlayer'
  post    'showForUserInLeague' => 'events#showForUserInLeague'
  
  
  
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :meets
  resources :events do
    member do
      get :selectEntrant
      get :addEntrant
      get :removeEntrant
      get :enterResult
      post :claimAthlete
      post :dropAthlete
    end
  end
  resources :athletes
  
  resources :sprint_results
  resources :mid_results
  resources :jump_results
  resources :throw_results
  resources :league_settings
  resources :athlete_selections
  
  resources :leagues do
    member do
      get :searchLeague
      get :joinLeague
      post :addMember
      post :requestFriend
      get :inviteFriend
      get :boxScore
    end
  end
  resources :singleleague
  resources :league_messages,          only: [:create, :destroy]
end

app/models/league.rb
class League < ActiveRecord::Base
    has_many :active_league_memberships, class_name:  "LeagueMember",
                                  foreign_key: "league_id",
                                  dependent:   :destroy
                             
    has_many :active_athlete_selections, class_name: "AthleteSelection",
                                        foreign_key: "league_id",
                                        dependent: :destroy
                                        
    has_many :active_meet_scores, class_name: "MeetScore",
                                foreign_key: "league_id",
                                dependent: :destroy
                                        
    has_many :league_settings, dependent: :destroy
    
                                  
    has_many :members, through: :active_league_memberships, source: :user
    
    has_many :league_messages, dependent: :destroy
    
    validates :league_name, presence: true, length: {maximum: 64},
											uniqueness: true
											
	
	
 def self.search(search)
   if search
     find(:all, :conditions => ['name LIKE ?', "#{search}"])
   else
     find(:all)
   end
 end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  helper_method :searchLeague
  helper_method :joinLeague
  helper_method :addMember
  helper_method :inviteFriend
  helper_method :requestFriend
  helper_method :boxScore
  
  def show
    #@league = Meet.find(params[:id])
    #I'm not sure if you meant to use Meet here so I'll keep this line in comment
    #For now I'll use League.find --Xi
    @league = League.find(params[:id])
    session[:current_league] = @league.id
    @leaguefromSessions = session[:current_league]
    @league_messages = @league.league_messages.paginate(page: params[:page])
    @league_message = @league.league_messages.build
    @thisUser = User.find_by_session_token(session[:session_token])
  end

  def new
    @league = League.new
  end
  
  def show_all
    @allLeagues = League.all()
    
    if params[:search]
      @allLeagues = League.search(params[:search])
    else
      @allLeagues = League.all()
    end
    
  end
  
  def index
    @thisUser = User.find_by_session_token(session[:session_token])
    @leagues = @thisUser.leagues()
  end
  
  def searchLeague
    @thisUser = User.find_by_session_token(session[:session_token])
    @myleagues = @thisUser.leagues
    @leagues = League.all() -  @myleagues
  end
  
  def inviteFriend
    #view for entering friend's email address
    @league = League.find(session[:current_league])
    @thisUser = User.find_by_session_token(session[:session_token])
  end
  
  def requestFriend
    @friend = User.new(friend_params)
    @league = League.find(session[:current_league])
    UserMailer.invite_friend(@friend, @league).deliver
    redirect_to league_path(@league)
  end
  
  def joinLeague
    @league = League.find(params[:id])
    @thisUser = User.find_by_session_token(session[:session_token])
  end
  
  def addMember
    @leagueInfo = League.new(league_params)
    @existingLeague = League.find(@leagueInfo.id)
    if(@leagueInfo.pass_code == @existingLeague.pass_code)
      @thisUser = User.find_by_session_token(session[:session_token])
      @thisUser.active_league_memberships.create(league_id: @existingLeague.id, user_id: @thisUser.id)
      @existingLeague.league_messages.create!(user: User.find_by(user_id: 'Admin'), content: "Welcome #{view_context.link_to @thisUser.user_id, @thisUser} to #{@existingLeague.league_name}!")
      flash[:notice] = "You have successcully joined #{@existingLeague.league_name}!"
      redirect_to leagues_path
    else
      flash[:warning] = "Wrong passcode please re-enter!"
      redirect_to joinLeague_league_path(@existingLeague)
    end
  end
  
  def create
    @league = League.new(league_params)    # Not the final implementation!
    @creator = User.find_by_session_token(session[:session_token])
    @league.creator_id = @creator.id #this needs to be the user's id
    if @league.save
      @savedLeague = League.find_by(:league_name => @league.league_name)
      @creator.active_league_memberships.create(league_id: @savedLeague.id, user_id: @creator.id)
      @settings = @savedLeague.league_settings.build(league_id: @league_id, standard_scoring: true, pr_bonus: true, wr_bonus: true,
                nr_bonus: true, fastest_start_bonus: true, split_leader_bonus: true, best_of_round_bonus: true, 
                athlete_select_option: "1")
      @settings.save
      flash[:notice] = "#{@league.league_name} successcully created."
      redirect_to leagues_path
    else
      render 'new'
    end
  end
  
  def standings
    @league = League.find(session[:current_league])
    
    meets = Meet.where(:released => true)
    @thisUser = User.find_by_session_token(session[:session_token])
    members = @league.members
    meets.each do |m|
      scores = MeetScore.where(:league_id => @league.id, :meet_id => m.id)
      if(m.scored == true && scores.empty?)
        members.each do |member|
          selections = AthleteSelection.where(:meet_id => m.id, :user_id => member.id, :league_id => @league.id)
          score = nil
          selections.each do |selection|
            if(score == nil)
              score = selection.points
            else
              score += selection.points
            end
          end
          MeetScore.create(:meet_id => m.id, :user_id => member.id, :league_id => @league.id, :points => score)
        end
      end
    end
    
    @members = @league.members
  end
  
  def scoreboard
    @league = League.find(session[:current_league])
    @scores = MeetScore.where(:league_id => @league.id)
    @people = @league.members
    session[:current_meet] = 1
    @thisUser = User.find_by_session_token(session[:session_token])
    @meets = Meet.where(:released => true)
   # @meets.each do |m|
    #  m.scores= m.active_meet_scores
   # end
    if(@meets.empty?)
      @first = 0
    else
      @first = @meets.first.id
    end
   # @meet = @meets.first
  end
  
  def boxScore
    @thisUser = User.find_by_session_token(session[:session_token])
    @league = League.find(session[:current_league])
    @user = User.find(params[:id])
    #@meet = Meet.find(session[:current_meet])
    @meet = Meet.find(params[:meet_id])
    @athlete_selections = AthleteSelection.where(:user_id => params[:id], :meet_id => @meet.id, :league_id => @league.id)
    # .all is for developing Please fix it later
  end
  
  def myteam
    
   @availablemeets = []
   @meets = Meet.all()
   @thisUser = User.find_by_session_token(session[:session_token])
   @league = League.find(session[:current_league])
   @meets.each do |meet|
     @availablemeets << meet if meet.released == true
    end
  end
  
  def settings
    @thisUser = User.find_by_session_token(session[:session_token])
    @league = League.find(session[:current_league])
    @settings = @league.league_settings.first
  end
  
  def meet_scoreboard
    #@meet = Meet.find(params[:id]) #change this to be the current meet we just got
    @meet = Meet.find(2)
    session[:current_meet] = params[:id]
    #render :partial=>'meet_scoreboard'
  end
  
  def edit_league_setting
    
  end
  
  private

    def league_params
      params.require(:league).permit(:league_name, :pass_code, :id)
    end
    
    def friend_params
      params.require(:user).permit(:email, :user_id)
    end
end

app/views/leagues/_meet_scoreboard.html.erb
<h3>Scores for <%= meet.meet_name %></h3>
<table id="example" class="display example" cellspacing="0" width="100%">
    <thead>
        <tr>
            <td>User</td>
            <td>Score</td>
            <td>Box Score</td>
        </tr>
    </thead>
    <tbody>
        <% people.each do |p| %>
            <tr>
                <td><%= p.user_id %></td>
                <td><% scores.each do |s| %>
                        <% if(s.user_id == p.id && s.meet_id == meet.id) %>
                            <%= s.points %>
                        <% end %>
                    <% end %>
                </td>
                <td><%= link_to 'Box Score', "/leagues/#{p.id}/boxScore/?meet_id=#{meet.id}" %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/leagues/boxScore.html.erb
  <center><h2 id="header">League: <%=League.find(session[:current_league]).league_name %></h2></center>
 <center><div class="container" id = "leagueNavBar">
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'League Home', league_path(League.find(session[:current_league])) %></li>
                <li><%= link_to 'My Team', myteam_path %></li>
                <li><%= link_to 'Standings', standings_path %></li>
                <li><%= link_to 'Scoreboard', scoreboard_path %></li>
                <li><%= link_to 'League Settings', settings_path %></li>
                <% if (@league.creator_id == @thisUser.id) %>
                   <li><%= link_to 'Invite Friends', inviteFriend_league_path(@league) %></h4>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
   </div></center>
   
   <div class = "container">
 
      <div class="jumbotron">
        <h3><%= @user.user_id %> Box Score For <%= @meet.meet_name %></h3>
      </div>
      
      <table>
          <% @totalScore =0 %>
          <tr>
              <th>Athlete First Name</th>
              <th>Athlete Last Name</th>
              <th>Event</th>
              <th>Result</th>
              <th>Score</th>
          </tr>
            <% if @athlete_selections == nil %>
              <tr>
              <td>no entry</td>
              </tr>

            <% else %>
              <% @athlete_selections.each do |s|%>
              <% @event_entrant = EventEntrant.find_by_event_id_and_athlete_id(s.event_id,s.athlete_id) %>
              <% @athlete = Athlete.find_by_id(@event_entrant.athlete_id) %>
              <% @event = Event.find_by_id(@event_entrant.event_id) %>
              <tr>
                  <td width=15%><%= @athlete.first_name %></td>
                  <td width=15%><%= @athlete.last_name %></td>
                  <td width=25%><%= @event.event_name %></td>
                  <td width=15%> -- </td>
                  <td width=15%><%= @event_entrant.points %> </td>
                  <% if(@event_entrant.points == nil) %>
                  <% @event_entrant.points = 0 %>
                  <% end %>
                  <% @totalScore = @totalScore + @event_entrant.points %>
              </tr>
              <% end %>
            <% end %>
      </table>
      
      <table>
        <tr>
          <td width = 90%>Total Points</td>
          <td width = 10%><%= @totalScore %></td>
        </tr>
      </table>
      
      <li><%= link_to 'Back to scoreboard', scoreboard_path %><li>
   </div>

app/views/leagues/index.html.erb
<script>
    $(document).ready(function() {
    $('#example').DataTable();
    } );
</script>

<div class = "container">
   <h2>Your League List</h2>
   <h3><a><%= link_to "Create New League", new_league_path, method: "get" %></a></h3>
     <table id="example" class="display" cellspacing="0" width="100%">
       <thead>
         <td>League Name</td>
         <td>Enter</td>
       </thead>
       <tbody>
          <h5><% @leagues.each do |p| %></h5>
          <tr>
              <td><%= p.league_name %></td>
              <td>
                 <%= link_to 'Enter', league_path(p) %>
              </td>
           </tr>
          <% end %>
       </tbody>
     </table>
</div>

app/views/leagues/inviteFriend.html.erb
<div class = "container" id = "invite">  
   <% provide(:title, 'Invite new member') %>
  <center><div class="container" id = "leagueNavBar">
    <center><h2 id="header">League: <%=League.find(session[:current_league]).league_name %></h2></center>
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'League Home', league_path(League.find(session[:current_league])) %></li>
                <li><%= link_to 'My Team', myteam_path %></li>
                <li><%= link_to 'Standings', standings_path %></li>
                <li><%= link_to 'Scoreboard', scoreboard_path %></li>
                <li><%= link_to 'League Settings', settings_path %></li>
                <% if (@league.creator_id == @thisUser.id) %>
                   <li><%= link_to 'Invite Friends', inviteFriend_league_path(@league) %></h4>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
   </div></center>
   <h2>Invite A Friend to <%=@league.league_name %></h2>
  <div class="col-md-6 col-md-offset-3" id = "invitebyemail">
      <br/>
      <%= form_for(:user, url: requestFriend_league_path) do |f| %>
      
        <%= f.label :email, "Friend Email: " , :id => "label"%>
        <%= f.text_field :email, :value => "" %>
        
        </br>
        </br>
        <%= f.submit "Send Invite", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/leagues/joinLeague.html.erb
<div class = "container" id = "invite">
   <h2>League: <%=@league.league_name %></h2>
  <div class="col-md-6 col-md-offset-3" >
      <br/>
      <%= form_for(:league, url: addMember_league_path) do |f| %>
      
        <%= f.label :pass_code, "Enter Code: " , :id => "label"%>
        <%= f.text_field :pass_code,:value=>"", :required => true %>
        
        <%= f.hidden_field :id, :value => @league.id %>
        
        </br>
        </br>
        <%= f.submit "Save", class: "btn btn-primary" %>
      <% end %>
  </div>

</div>
  

app/views/leagues/myteam.html.erb
<script>
    $(document).ready(function() {
    $('#example').DataTable();
    } );
</script>
 <center><div class="container" id = "leagueNavBar">
     <center><h2 id="header">League: <%=@league.league_name %></h2></center>
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'League Home', league_path(@league) %></li>
                <li><%= link_to 'My Team', myteam_path %></li>
                <li><%= link_to 'Standings', standings_path %></li>
                <li><%= link_to 'Scoreboard', scoreboard_path %></li>
                <li><%= link_to 'League Settings', settings_path %></li>
                <% if (@league.creator_id == @thisUser.id) %>
                   <li><%= link_to 'Invite Friends', inviteFriend_league_path(@league) %></h4>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
   </div></center>
<div id = "divider">
    <div class = "container" id = "meets">
      <div>
         <h3>Set Your Team For The Following Upcoming Meets!</h3>
         <br></br>
      </div>
      <div>
        <table id="example" class="display" cellspacing="0" width="100%">
            <thead>
                <td>Meet</td>
                <td>Location</td>
                <td>Start Date</td>
                <td>End Date</td>
            </thead>
            <tbody>
               <% @availablemeets.each do |p| %>
                <tr>
                    <td><%= link_to "#{p.meet_name}", meet_path(p), method: "get" %></td>
                    <td><%= p.location_city %>, <%= p.location_country %></td>
                    <td><%= p.start_date %></td>
                    <td><%= p.end_date %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>
</div>

app/views/leagues/new.html.erb
<div class = "container" id = "newleague">  
   <% provide(:title, 'Create new leagues') %>
  <h2>Create A New League</h2>

  <div class="col-md-6 col-md-offset-3" id = "createleague">
      <br/>
      <%= form_for(:league, url: leagues_path) do |f| %>
      
        <%= f.label :league_name, "League Name: " %>
        <%= f.text_field :league_name %>

        <%= f.label :pass_code, "League Password: " %>
        <%= f.text_field :pass_code %>
        </br>
        </br>
        <%= f.submit "Create League", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/leagues/scoreboard.html.erb
<script>
  $(function(){
    $('.board').hide();
    $('#id-' + <%= @first %>).show();
    
    $('.list-group-item').click(function( ){
      $('.board').hide();
      $("a.active").removeClass("active");
      var idStr = $(this).attr("id");
      var length = idStr.length;
      length = length - 2
      var id = idStr.substr(2,length)
      $('#id-' + id).show();
      $(this).addClass("active");
    });
  });
</script>

<script>
    $(document).ready(function() {
    $('.example').DataTable();
    } );
</script>
  
  <center><h2 id="header">League: <%=League.find(session[:current_league]).league_name %></h2></center>
 <center><div class="container" id = "leagueNavBar">
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'League Home', league_path(League.find(session[:current_league])) %></li>
                <li><%= link_to 'My Team', myteam_path %></li>
                <li><%= link_to 'Standings', standings_path %></li>
                <li><%= link_to 'Scoreboard', scoreboard_path %></li>
                <li><%= link_to 'League Settings', settings_path %></li>
                <% if (@league.creator_id == @thisUser.id) %>
                   <li><%= link_to 'Invite Friends', inviteFriend_league_path(@league) %></h4>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
   </div></center>
   <div class = "container">
      <div class="jumbotron">
        <h3><%= @league.league_name %> Meet Scoreboards </h3>
      </div>
      <div class="container">
        <div class="well col-sm-4">
          <h3>Meets</h3>
          <div class="list-group">
            <% i = 1 %>
            <% @meets.each do |meet| %>
              <% if(i == 1) %>
                <a id='a-<%= meet.id %>' class="list-group-item active"><%= meet.meet_name %></a>
                <% i = i + 1 %>
              <% else %>
                <a id='a-<%= meet.id %>' class="list-group-item"><%= meet.meet_name %></a>
              <% end %>
            <% end %>
          </div>
        </div>
        <% @meets.each do |meet| %>
        <div id="id-<%=meet.id %>" class="well col-sm-4 board">
          <%= render(:partial => "meet_scoreboard", :locals => {:meet => meet, :people => @people,
                      :scores => @scores }) %>
        </div>
        <% end %>
      </div>
   </div>
   

app/views/leagues/searchLeague.html.erb
<script>
    $(document).ready(function() {
    $('#example').DataTable();
    } );
</script>
<br/>
<div class = "container">
  <h2>League List</h2>
     <table id="example" class="display" cellspacing="0" width="100%">
       <thead>
         <td>League Name</td>
         <td>Join</td>
       </thead>
       <tbody>
          <h5><% @leagues.each do |p| %></h5>
          <tr>
              <td><%= p.league_name %></td>
              <td><%= link_to 'Join', joinLeague_league_path(p) %></td>
           </tr>
          <% end %>
          <h5><% @myleagues.each do |p| %></h5>
          <tr>
              <td><%= p.league_name %></td>
              <td><%= link_to 'Enter', league_path(p) %></td>
           </tr>
          <% end %>
       </tbody>
     </table>
  
</div>

app/views/leagues/settings.html.erb
 <center><div class="container" id = "leagueNavBar">
   <center><h2 id="header">League: <%=League.find(session[:current_league]).league_name %></h2></center>
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'League Home', league_path(League.find(session[:current_league])) %></li>
                <li><%= link_to 'My Team', myteam_path %></li>
                <li><%= link_to 'Standings', standings_path %></li>
                <li><%= link_to 'Scoreboard', scoreboard_path %></li>
                <li><%= link_to 'League Settings', settings_path %></li>
                <% if (@league.creator_id == @thisUser.id) %>
                   <li><%= link_to 'Invite Friends', inviteFriend_league_path(@league) %></h4>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
   </div></center>
   <div class = "container">
      <div class="well well-sm">
        <h2>League Settings</h2>
      </div>
    </br>
    <div class="jumbotron">
      <h1>Points</h1>
      <h4>Default Points: <%= @settings.standard_scoring %></h4>
      </br>
      <h4>Correct Place Bonus: <%= @settings.exact_place_bonus %></h4>
      </br>
      <h4>PR Bonus: <%= @settings.pr_bonus %></h4>
      </br>
      <h4>NR Bonus: <%= @settings.nr_bonus %></h4>
      </b4>
      <h4>WR Bonus: <%= @settings.wr_bonus %></h4>
      </b4>
      <h4>Best Of Round Bonus: <%= @settings.best_of_round_bonus %></h4>
      </br>
      <h4>Split Leader Bonus: <%= @settings.split_leader_bonus %></h4>
      </br>
      <h4>Fastest Start Bonus: <%= @settings.fastest_start_bonus %></h4>
      </br>
    </div>
    <div class="jumbotron">
      <h1>Athlete Selection</h1>
      </br>
      <% if(@settings.athlete_select_option == 1) %>
        <h4>Select 3 athletes for every event</h4>
      <% elsif(@settings.athlete_select_option == 2) %>
        <h4>Select 1 event per event type, and select 3 athletes for each event selected</h4>
      <% elsif(@settings.athlete_select_option == 3) %>
        <h4>Pick order of every athlete in every event</h4>
      <% else %>
        <h4>Select 1 event per event type, and select the order for every athlete in those events</h4>
      <% end %>
    </div>
  </div>
</div>
<div id="border">
    <div>
        
    </div>
</div>

app/views/leagues/show.html.erb
<div class = "container" id = "invite">  
   <center><h2 id="header">Welcome to <%=@league.league_name %></h2></center>
   <center><div class="container" id = "leagueNavBar">
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'League Home', league_path(League.find(session[:current_league])) %></li>
                <li><%= link_to 'My Team', myteam_path %></li>
                <li><%= link_to 'Standings', standings_path %></li>
                <li><%= link_to 'Scoreboard', scoreboard_path %></li>
                <li><%= link_to 'League Settings', settings_path %></li>
                <% if (@league.creator_id == @thisUser.id) %>
                   <li><%= link_to 'Invite Friends', inviteFriend_league_path(@league) %></h4>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
   </div></center>
</div>
<div class="container">
  <h3>League Info</h3>
  <table id = "info">
    <tr>
      <% @leagueCreator = User.find_by_id(@league.creator_id) %>
      <td>League Creator:  </td>
      <td class ="infocol">
         <%if @leagueCreator != nil %>
            <%=@leagueCreator.user_id %>
         <%end %>
      </td> 
    </tr>
    <tr>
      <td>Number of Members:   </td>
      <td class ="infocol">   <%= @league.members.count %></td>
    </tr>
    <tr>
      <td>Passcode:  </td>
      <td class ="infocol"><%= @league.pass_code %></td>
    </tr>
  </table>
  <% if @league.league_messages.any? %>
      <h3>League Messages (<%= @league.league_messages.count %>)</h3>
      <ol class="league_messages">
        <%= render @league_messages %>
      </ol>
      <%= will_paginate @league_messages %>
  <% end %>
  <div class="row">
    <aside class="container">
      <section class="league_message_form">
        <%= render 'shared/league_message_form' %>
      </section>
    </aside>
  </div>
</div>

app/views/leagues/show_all.html.erb
<div class = "container" id = "leagues">

<h2>Search For a League</h2>
<%= form_tag(show_all_path, :method => 'get', :id => "search-league-form") do %>
    <div> <%= text_field_tag :search, params[:search] %></div>
    <div> <%= submit_tag "Search", :name => nil %></div>
<% end %>
   
   <h2>League List</h2>
   <table width = 50%>
       <tr>
           <td>League Name</td>
           <td>Creator</td>
           <td>Players</td>
       </tr>
       <% @allLeagues.each do |league| %>
       <tr>
           <td><%=link_to league.league_name, league_path(league) %></td>
           <td><%=league.creator_id %></td>
           <td><%=league.league_messages.count %></td>
       </tr>
       <% end %>
   </table>

app/views/leagues/standings.html.erb
 <center><div class="container" id = "leagueNavBar">
   <center><h2 id="header">League: <%=League.find(session[:current_league]).league_name %></h2></center>
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'League Home', league_path(League.find(session[:current_league])) %></li>
                <li><%= link_to 'My Team', myteam_path %></li>
                <li><%= link_to 'Standings', standings_path %></li>
                <li><%= link_to 'Scoreboard', scoreboard_path %></li>
                <li><%= link_to 'League Settings', settings_path %></li>
                <% if (@league.creator_id == @thisUser.id) %>
                   <li><%= link_to 'Invite Friends', inviteFriend_league_path(@league) %></h4>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
  </div></center>
  <div class="container">
    <div class="jumbotron">
      <h3 align="center">League Standings</h3>
    </div>
    <div class="well">
      <table class="table">
        <thead>
          <tr>
            <th>Position</th>
            <th>User</th>
            <th>Points</th>
          </tr>
        </thead>
        <tbody>
          <% count = 0 %>
          <% @members.sort {|a,b| b.totalScore <=> a.totalScore }.each do |member| %>
            <% count += 1 %>
            <tr>
              <th scope="row"><%= count %></th>
              <td><%= member.user_id %></td>
              <td><%= member.totalScore %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>