config/routes.rb
Rails.application.routes.draw do
  root            'static_pages#home'
  get    'about'   => 'static_pages#about'
  post    'recent_meet' => 'static_pages#recent_meet'
  get   'show_all' => 'leagues#show_all'
  post  'scoring_rules' => 'static_pages#scoring_rules'
  post  'releaseMeet' => 'meets#releaseMeet'
  post 'scoreMeet' => 'meets#scoreMeet'
  get    'standings' => 'leagues#standings'
  get    'scoreboard'=> 'leagues#scoreboard'
  get    'myteam'  => 'leagues#myteam'
  get    'settings'=> 'leagues#settings'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'current_user' => 'sessions#show'
  delete  'meetdetail'  => 'meets#destroy'
  delete  'eventdetail'  => 'events#destroy'
  post    'addSelectedPlayer' => 'events#addSelectedPlayer'
  post    'showForUserInLeague' => 'events#showForUserInLeague'
  
  
  
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :meets
  resources :events do
    member do
      get :selectEntrant
      get :addEntrant
      get :removeEntrant
      get :enterResult
      post :claimAthlete
      post :dropAthlete
    end
  end
  resources :athletes
  
  resources :sprint_results
  resources :mid_results
  resources :jump_results
  resources :throw_results
  resources :league_settings
  resources :athlete_selections
  
  resources :leagues do
    member do
      get :searchLeague
      get :joinLeague
      post :addMember
      post :requestFriend
      get :inviteFriend
      get :boxScore
    end
  end
  resources :singleleague
  resources :league_messages,          only: [:create, :destroy]
end

app/models/jump_result.rb
class JumpResult < ActiveRecord::Base
    belongs_to :event, class_name: "Event"
    belongs_to :athlete, class_name: "Athlete"
    
    def name
        @name
    end
    
    def name= val
        @name = val
    end
end

app/controllers/jump_results_controller.rb
class JumpResultsController < ApplicationController
  
  def show
    @event = Event.find(session[:current_event])
    @results = JumpResult.where(:event_id => @event.id)
    @thisUser = User.find_by_session_token(session[:session_token])
    @results.each do |r|
        athlete = Athlete.find(r.athlete_id)
        r.name= athlete.first_name + " " + athlete.last_name
    end
  end

  def new
    @athlete = Athlete.find(session[:current_athlete])
    @thisUser = User.find_by_session_token(session[:session_token])
    @event = Event.find(session[:current_event])
  end
  
  def create
    @event = Event.find(session[:current_event])
    @thisUser = User.find_by_session_token(session[:session_token])
    @athleteID = session[:current_athlete]
    @r = JumpResult.new(result_params)
    @event.active_jump_results.create(event_id: @event.id, athlete_id: @athleteID, place: @r.place, best_jump: @r.best_jump, 
          best_of_round: @r.best_of_round,jump_1: @r.jump_1, jump_2: @r.jump_2, jump_3: @r.jump_3, jump_4:
          @r.jump_4,jump_5: @r.jump_5, jump_6: @r.jump_6, pr: @r.pr, nr: @r.nr, wr: @r.wr)
          
    points = nil
    if(@r.place == 1)
      points = 10
    elsif(@r.place == 2)
      points = 8
    elsif(@r.place == 3)
      points = 6
    elsif(@r.place == 4)
      points = 5
    elsif(@r.place == 5)
      points = 4
    elsif(@r.place == 6)
      points = 3
    elsif(@r.place == 7)
       points = 2
    elsif(@r.place == 8)
      points = 1
    end
    
    if(@r.wr)
      if(points == nil)
        points = 12
      else
        points = points + 12
      end
    elsif(@r.nr)
      if(points == nil)
        points = 6
      else
        points = points + 6
      end
    elsif(@r.pr)
      if(points == nil)
        points = 2
      else
        points = points + 2
      end
    end
    
    if(points == nil)
      points = best_of_round
    else
      points = points + (best_of_round)
    end
    
    if(points == nil)
      points = 0
    end
      
    @entrant = EventEntrant.find_by(:athlete_id => @athleteID, :event_id => @event.id)
    @entrant.update_attribute(:points, points)
    
    redirect_to event_path(@event)
  end
  
  def index
      
  end
  
  def destroy
    @current_meet = Meet.find(session[:current_meet])
    @result = JumpResult.find(params[:id])
    @result.destroy
    #flash[:notice] = "Event '#{@event.event_name}' deleted."
    redirect_to meet_path(@current_meet)
  end
 
  private

    def result_params
      params.require(:jump_result).permit(:event_id, :athlete_id, :pr, :nr, :wr, :best_of_round, :place, :best_jump, :jump_1, 
        :jump_2, :jump_3, :jump_4, :jump_5, :jump_6)
    end
end

app/views/jump_results/index.html.erb
<h2>Jump Index</h2>

app/views/jump_results/new.html.erb
<div class = "container" id = "newmeet">
   <% provide(:title, 'Create New Meets') %>
  <h2>Enter Result for <%= @athlete.first_name %> <%= @athlete.last_name %> for <%= @event.event_name %></h2>
  <div class="col-md-6 col-md-offset-3">
      <br/>
      <%= form_for(:jump_result, url: jump_results_path) do |f| %>
      
        <%= f.label :best_jump, "Best Jump (meters): " %>
        <%= f.number_field :best_jump, :step => 'any', :required => true %>

        <%= f.label :place, "Place: " %>
        <%= f.number_field :place, :required => true%>

        <%= f.label :jump_1, "Round 1: " %>
        <%= f.number_field :jump_1, :step => 'any', :required => false %>
  
        <%= f.label :jump_2, "Round 2: " %>
        <%= f.number_field :jump_2, :step => 'any', :required => false%>
        
        <%= f.label :jump_3, "Round 3: " %>
        <%= f.number_field :jump_3, :step => 'any', :required => false %>
        
        <%= f.label :jump_4, "Round 4: " %>
        <%= f.number_field :jump_4, :step => 'any', :required => false %>
        
        <%= f.label :jump_5, "Round 5: " %>
        <%= f.number_field :jump_5, :step => 'any', :required => false %>
        
        <%= f.label :jump_6, "Round 6: " %>
        <%= f.number_field :jump_6, :step => 'any', :required => false %>
        
        <%= f.label :pr, "Personal Record: " %>
        <%= f.check_box :pr %>
        
        <%= f.label :nr, "National Record: " %>
        <%= f.check_box :nr %>
        
        <%= f.label :wr, "World Record: " %>
        <%= f.check_box :wr %>
        
        <%= f.label :best_of_round, "Instances of Round Leader: " %>
        <%= f.number_field :best_of_round, :value => "0" %>
        </br>
        </br>
        <%= f.submit "Save Result", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>  

app/views/jump_results/show.html.erb
<script>
    $(document).ready(function() {
    $('#example').DataTable();
    } );
</script>
<div class = "container" id = "results">
   <% provide(:title, 'Results') %>
  <h2>Event Detail</h2>
  <h5>Event: <%= @event.event_name %></h5> 
  <h5>Event type: Throws</h5>
  <div>
    <h3>Results</h3>
    <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <td>Place</td>
            <td>Name</td>
            <td>Meters</td>
            <td>Round 1</td>
            <td>Round 2</td>
            <td>Round 3</td>
            <td>Round 4</td>
            <td>Round 5</td>
            <td>Round 6</td>
            <% if(@thisUser.role == "admin") %>
            <td>Delete<td>
            <% end %>
        </thead>
        <tbody>
           <% @results.each do |p| %>
            <tr>
                <td><%= p.place %></td>
                <td><%= p.name %></td>
                <td><%= p.best_jump %></td>
                <td><%= p.jump_1 %></td>
                <td><%= p.jump_2 %></td>
                <td><%= p.jump_3 %></td>
                <td><%= p.jump_4 %></td>
                <td><%= p.jump_5 %></td>
                <td><%= p.jump_6 %></td>
                <% if(@thisUser.role == "admin") %>
                    <td><%= button_to 'Delete', jump_result_path(p), :method => :delete, :confirm => 'Are you sure?'%><td>
                <% end %>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>