config/routes.rb
Rails.application.routes.draw do
  root            'static_pages#home'
  get    'about'   => 'static_pages#about'
  post    'recent_meet' => 'static_pages#recent_meet'
  get   'show_all' => 'leagues#show_all'
  post  'scoring_rules' => 'static_pages#scoring_rules'
  post  'releaseMeet' => 'meets#releaseMeet'
  post 'scoreMeet' => 'meets#scoreMeet'
  get    'standings' => 'leagues#standings'
  get    'scoreboard'=> 'leagues#scoreboard'
  get    'myteam'  => 'leagues#myteam'
  get    'settings'=> 'leagues#settings'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'current_user' => 'sessions#show'
  delete  'meetdetail'  => 'meets#destroy'
  delete  'eventdetail'  => 'events#destroy'
  post    'addSelectedPlayer' => 'events#addSelectedPlayer'
  post    'showForUserInLeague' => 'events#showForUserInLeague'
  
  
  
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :meets
  resources :events do
    member do
      get :selectEntrant
      get :addEntrant
      get :removeEntrant
      get :enterResult
      post :claimAthlete
      post :dropAthlete
    end
  end
  resources :athletes
  
  resources :sprint_results
  resources :mid_results
  resources :jump_results
  resources :throw_results
  resources :league_settings
  resources :athlete_selections
  
  resources :leagues do
    member do
      get :searchLeague
      get :joinLeague
      post :addMember
      post :requestFriend
      get :inviteFriend
      get :boxScore
    end
  end
  resources :singleleague
  resources :league_messages,          only: [:create, :destroy]
end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :meet
    
    has_many :active_event_entrants, class_name:  "EventEntrant",
                                  foreign_key: "event_id",
                                  dependent:   :destroy
                                  
    has_many :active_sprint_results, class_name: "SprintResult",
                                    foreign_key: "event_id",
                                    dependent: :destroy
                                    
    has_many :active_mid_results, class_name: "MidResult",
                                    foreign_key: "event_id",
                                    dependent: :destroy
                                    
    has_many :active_throw_results, class_name: "ThrowResult",
                                    foreign_key: "event_id",
                                    dependent: :destroy
                                    
    has_many :active_jump_results, class_name: "JumpResult",
                                    foreign_key: "event_id",
                                    dependent: :destroy
                                    
    has_many :active_athlete_selections, class_name: "AthleteSelection",
                                        foreign_key: "event_id",
                                        dependent: :destroy                                
                                  
    has_many :entrants, through: :active_event_entrants, source: :athlete
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  helper_method :selectEntrant
  helper_method :addEntrant
  helper_method :removeEntrant
  helper_method :enterResult
  helper_method :dropAthlete
  helper_method :claimAthlete
  
  def set_current_user
    @current_user ||=	session[:session_token] && User.find_by_session_token(session[:session_token])
  end
  include SessionsHelper
  
  def show
    @event = Event.find(params[:id])
    session[:current_event] = @event.id
    @entrants = @event.entrants
    @meet = Meet.find(session[:current_meet])
    thisUser = User.find_by_session_token(session[:session_token])
    if(thisUser.role == "user")
      league_id = session[:current_league]
      event_id = @event.id
      selections = AthleteSelection.where(:user_id => thisUser.id, :league_id => league_id, :event_id => event_id)
      count = nil
      @entrants.each do |entrant|
        selections.each do |pick|
          if(pick.athlete_id == entrant.id)
            entrant.selected = true
            if(count == nil)
              count = 1
            else
              count = count + 1
            end
          end
        end
      end
      @count = count
    end
  end
  
  def dropAthlete
    @athlete = Athlete.find(params[:id])
    league_id = session[:current_league]
    event_id = session[:current_event]
    meet_id = session[:current_meet]
    thisUser = User.find_by_session_token(session[:session_token])
    AthleteSelection.delete_all(:athlete_id => @athlete.id, :league_id => league_id, :event_id => event_id, 
                            :meet_id => meet_id, :user_id => thisUser.id)
                            
    redirect_to event_path(event_id)
    
  end
  
  def claimAthlete
    @athlete = Athlete.find(params[:id])
    league_id = session[:current_league]
    event_id = session[:current_event]
    meet_id = session[:current_meet]
    thisUser = User.find_by_session_token(session[:session_token])
    AthleteSelection.create(:athlete_id => @athlete.id, :league_id => league_id, :event_id => event_id, 
                            :meet_id => meet_id, :user_id => thisUser.id)
                            
    redirect_to event_path(event_id)
  end
  
  def addSelectedPlayer
    
   # @athlete = Athlete.find(params[:id])
   # @athlete.selected = true
    #@thisUser = User.find_by_session_token(session[:session_token])
        
    @user = User.find(session[:current_user])
    @event = Event.find(session[:current_event])
    @legue = League.find(session[:current_league])
    @meet = Meet.find(session[:current_meet])
    @athlete = Athlete.find(session[:current_athlete])
    
    @user.league.meet.event.athlete.selected = true
    
    
    
    
    
    
  end


  def new
    @event = Event.new
  end
  
  def create
    @current_meet = Meet.find(session[:current_meet])
    @event = @current_meet.events.build(event_params)
    #@event = Event.new(event_params)    # Not the final implementation!
    if @event.save
      flash[:success] = "Created #{@event.event_name}!"
      redirect_to meet_path(@current_meet)
    else
      render 'new'
    end
  end
  
  def destroy
    @current_meet = Meet.find(session[:current_meet])
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Event '#{@event.event_name}' deleted."
    redirect_to meet_path(@current_meet)
  end
  
  def addEntrant
    #this receives the id of the athlete to create an eventEntrant thing.
    @athlete = Athlete.find(params[:id])
    @event = Event.find(session[:current_event])
    @event.active_event_entrants.create(event_id: @event.id, athlete_id: @athlete.id)
    
    redirect_to event_path(@event)
  end
  
  def selectEntrant
    #this is to return the view to search/select an athlete
    @event = Event.find(params[:id])
    session[:current_event] = @event.id
    @meet = Meet.find(@event.meet_id)
    @athletes = Athlete.all()
  end
  
  def removeEntrant
    entryId = params[:id]
    @event = Event.find(session[:current_event])
    @entry = EventEntrant.find_by(:event_id => @event.id, :athlete_id => entryId)
    @entry.destroy
    
    redirect_to event_path(@event)
  end
  
  def enterResult
    @athlete = Athlete.find(params[:id])
    @event = Event.find(session[:current_event])
    session[:current_athlete] = @athlete.id
    if(@event.event_type == 0)
      redirect_to new_sprint_result_path(@athlete)
    elsif(@event.event_type == 1)
      redirect_to new_mid_result_path(@athlete)
    elsif(@event.event_type == 2)
      redirect_to new_throw_result_path(@athlete)
    else
      redirect_to new_jump_result_path(@athlete)
    end
      
  end
  
  private

    def event_params
      params.require(:event).permit(:event_name, :event_type)
    end
end

app/views/events/new.html.erb
<div class = "container" id = "newevent">
   <% provide(:title, 'Create new Events') %> 
  <h2>Enter new event details</h2>
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(:event, url: events_path) do |f| %>
      
        <%= f.label :event_name, "Event Name: " %>
        <%= f.text_field :event_name %>

        <%= f.label :event_type, "Event Type: " %>
        <%= f.text_field :event_type %>

        </br>
        </br>
        <%= f.submit "Save", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/events/selectEntrant.html.erb
<script>
    $(document).ready(function() {
    $('#example').DataTable();
    } );
</script>
<div class="container">
<% provide(:title,'Add Entrants') %>
<h2>Select an athlete to add to event: <%= @event.event_name %> for meet: <%= @meet.meet_name %>.</h2>
<div>
    <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <td>Name</td>
            <td>Country</td>
            <td>Birth Date</td>
        </thead>
        <tbody>
           <% @athletes.each do |p| %>
            <tr>
                <td><%= p.first_name %> <%= p.last_name %> <%= link_to "Add", addEntrant_event_path(p) %></td>
                <td><%= p.country %></td>
                <td><%= p.birth_date %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/events/show.html.erb
<script>
    $(document).ready(function() {
    $('#example').DataTable();
    } );
    
    $(document).ready(function() {
    $('#addOrDrop')
    
    
    
    } );
    
 
</script>
<div class = "container" id = "eventdetail">
   <% provide(:title, 'Event Info') %>
  <h2>Event Detail</h2>
  <h5>Event: <%= @event.event_name %></h5> 
  <h5>Event type:
    <% if(@event.event_type == 0) %>
        Sprint/Hurdle
        </br>
        <h3><%= link_to "Results", sprint_result_path(@event), method: "get" %></h3>
    <% end %>
    <% if(@event.event_type == 1) %>
        Mid Distance
        </br>
        <h3><%= link_to "Results", mid_result_path(@event), method: "get" %></h3>
    <% end %>
    <% if(@event.event_type == 2) %>
        Throws
        </br>
        <h3><%= link_to "Results", throw_result_path(@event), method: "get" %></h3>
    <% end %>
    <% if(@event.event_type == 3) %>
        Jumps
        </br>
        <h3><%= link_to "Results", jump_result_path(@event), method: "get" %></h3>
    <% end %>
  </h5>
    <% if logged_in? %>
      <% if @current_user.role == "admin" %>
        <h4><%= link_to "Add Entrant", selectEntrant_event_path(@event) %></h4>
      <%end%>
    <%end%>
  <div>
    <h3>Entrants</h3>
    <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <td>Name</td>
            <td>Country</td>
            <td>Birth Date</td>
            <td>Comments</td>
            <% if @current_user.role == "admin" %>
               <% if !@meet.scored %>
                  <td>Remove</td>
                  <td>Enter Result</td>
               <% end %>
            <% elsif !@meet.scored %>
                <td> Add or Drop</td>
            <% end %>
        </thead>
        <tbody>
           <% @entrants.each do |p| %>
            <tr>
                <td><%= link_to "#{p.first_name} #{p.last_name}", athlete_path(p), method: "get" %></td>
                <td><%= p.country %></td>
                <td><%= p.birth_date %></td>
                <td><%= p.notes %></td>
                <% if @current_user.role == "admin" %>
                   <td><%= link_to "Remove Entrant", removeEntrant_event_path(p), method: "get" %></td>
                   <td><%= link_to "Enter Result", enterResult_event_path(p), method: "get" %></td>
                <% else%>
                   <td><% if(p.selected) %>
                       <%= button_to "Drop" , dropAthlete_event_path(p), class: 'Drop'%>
                       <% elsif (@count != 3) %>
                       <%= button_to "Add" , claimAthlete_event_path(p), class: 'Add'%>
                       <% end %></td>
                <%end%>
            </tr>
          <%end%>
        </tbody>
    </table>
  </div>
   <% if logged_in? %>
      <% if @current_user.role == "admin" %>
        <label><%= button_to 'Delete Event', event_path(@event), :method => :delete, :confirm => 'Are you sure?'%></label>
      <%end%>
    <%end%>
</div>